name: Act Demo
run-name: Testing Actions ğŸš€
on: [push]
jobs:
  Min-Demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by."
      - run: echo "ğŸ§ This job is now running on a server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch."
